from typing import Dict, Any
import logging

logger = logging.getLogger("davinci-resolve-mcp")


def get_item_by_id(resolve, timeline_item_id: str):
    """
    Helper to find a TimelineItem by its unique ID (as mocked or generated by our tools).
    Note: Resolve API doesn't have native UUIDs for items that persist perfectly across sessions easily,
    but our 'get_timeline_items' generates them.

    If the ID matches the format we use (which might be just `uniqueId` property or something else),
    we try to find it.

    HOWEVER, iterating the whole timeline is expensive.

    Strategy:
    - Verify if `timeline_item_id` is passed.
    - Iterate all items in current timeline.
    - Check for ID match.
    """
    project_manager = resolve.GetProjectManager()
    project = project_manager.GetCurrentProject()
    timeline = project.GetCurrentTimeline()

    if not timeline:
        return None

    # Iterating all tracks... we only care about Video for Fusion effects
    track_count_video = timeline.GetTrackCount("video")

    for i in range(1, track_count_video + 1):
        items = timeline.GetItemListInTrack("video", i)
        if items:
            for item in items:
                # How do we get the ID?
                # Our `get_timeline_items` tool likely used `item.GetUniqueId()` (if v19) or just hash/properties.
                # Let's assume UniqueId exists in modern Resolve.
                try:
                    uid = item.GetUniqueId()
                    if str(uid) == str(timeline_item_id):
                        return item
                except Exception:
                    pass

                # Fallback: maybe the ID passed is just the name? (Risky)
                if item.GetName() == timeline_item_id:
                    return item

    return None


def add_fusion_effect(resolve, timeline_item_id: str, effect_name: str, settings: Dict[str, Any] = None) -> str:
    """
    Adds a Fusion effect node to the specified timeline item's composition.
    """
    item = get_item_by_id(resolve, timeline_item_id)
    if not item:
        return f"Error: Timeline item '{timeline_item_id}' not found."

    # 1. Get/Create Fusion Comp
    comp_count = item.GetFusionCompCount()
    if comp_count == 0:
        logger.info(f"Creating new Fusion Comp for item {item.GetName()}")
        try:
            # Just initializing it might be enough or we call AddFusionComp()
            # The API usually is item.AddFusionComp()
            item.AddFusionComp()
        except Exception as e:
            return f"Error creating Fusion Composition: {e}"

        # Refresh count
        comp_count = item.GetFusionCompCount()

    if comp_count == 0:
        return "Error: Failed to create/access Fusion Composition."

    # FIX: Use the latest composition (active one), not just index 1
    # Adding a comp pushes count up. Timeline usually displays the latest one.
    comp = item.GetFusionCompByIndex(comp_count)
    if not comp:
        return "Error: Fusion Composition object is null."

    # 2. Add Tool
    logger.info(f"Adding effect '{effect_name}' to comp")

    # "MediaOut1" is usually the final node. We want to insert before it?
    # Or just AddTool checks registry.
    # The command is comp.AddTool(id, x, y)

    # Helper to map friendly names to IDs if needed
    # e.g. "Vignette" -> "Vignette" (usually works)
    # "CameraShake" -> "CameraShake"

    try:
        new_tool = comp.AddTool(effect_name)
        if not new_tool:
            return f"Error: Failed to add tool '{effect_name}'. Check if name is correct."

        # 3. Apply Settings
        if settings:
            for key, val in settings.items():
                try:
                    # Check if it's a keyframe dictionary
                    # Expected format: {"keyframes": {frame_num: value, ...}}
                    if isinstance(val, dict) and "keyframes" in val:
                        kf_data = val["keyframes"]
                        logger.info(f"Applying keyframes for {key}: {len(kf_data)} points")
                        # Initialize BezierSpline via Lua for this key
                        try:
                            # Use comp.Execute to access tool by Name
                            # e.g. "ToolName.Gain = BezierSpline()"
                            init_cmd = f"{new_tool.Name}.{key} = BezierSpline()"
                            logger.info(f"Lua Init: {init_cmd}")
                            comp.Execute(init_cmd)
                        except Exception as e:
                            logger.warning(f"Lua Init failed for {key}: {e}")

                        for frame, kf_val in kf_data.items():
                            # Ensure frame is valid number
                            try:
                                f_num = float(frame)
                                # Use Lua for assignment: ToolName.Gain[frame] = val
                                kf_cmd = f"{new_tool.Name}.{key}[{f_num}] = {kf_val}"
                                logger.info(f"Lua Keyframe: {kf_cmd}")
                                comp.Execute(kf_cmd)
                            except Exception as kf_err:
                                logger.warning(f"Failed to set keyframe {key}@{frame}: {kf_err}")
                    else:
                        # Simple SetInput
                        new_tool.SetInput(key, val)
                        logger.info(f"Set {key}={val}")
                except Exception as ex:
                    logger.warning(f"Failed to set input {key}: {ex}")

        # 4. Connect to pipeline (Auto-wiring)
        # Standard Logic: MediaIn1 -> NewTool -> MediaOut1
        import traceback

        try:
            tool_list = comp.GetToolList(False)
            media_out = None
            media_in = None

            # Find MediaIn and MediaOut by checking ID or Name
            if tool_list:
                for _, tool in tool_list.items():
                    if tool.ID == "MediaOut" or "MediaOut" in tool.Name:
                        media_out = tool
                    elif tool.ID == "MediaIn" or "MediaIn" in tool.Name:
                        media_in = tool

            if media_out:
                # Get current input to MediaOut1
                current_input = media_out.GetInput("Input")  # standard input name for MediaOut

                if current_input:
                    # Disconnect current input from MediaOut and connect to NewTool Input
                    # Note: SetInput accepts a source Output.
                    # We want: Source -> NewTool -> MediaOut1

                    # Connect NewTool Input to whatever was feeding MediaOut
                    new_tool.SetInput("Input", current_input)

                    # Connect MediaOut Input to NewTool Output
                    media_out.SetInput("Input", new_tool.FindMainOutput(1))

                    logger.info("Successfully wired new tool into pipeline (inserted before MediaOut).")
                elif media_in:
                    # If MediaOut has no input, try connecting MediaIn -> NewTool -> MediaOut
                    new_tool.SetInput("Input", media_in.FindMainOutput(1))
                    media_out.SetInput("Input", new_tool.FindMainOutput(1))
                    logger.info("Successfully wired new tool into pipeline (between MediaIn and MediaOut).")

            return (
                f"Successfully added '{effect_name}' to item '{timeline_item_id}' (ID: {comp.GetAttrs()['COMPS_Name']})"
            )

        except Exception as e:
            logger.error(f"Error checking/connecting pipeline: {e}")
            return f"Added tool '{effect_name}' but failed to wire it: {e}"

    except Exception as e:
        import traceback

        tb = traceback.format_exc()
        logger.error(f"Error adding fusion effect: {tb}")
        return f"Error adding fusion effect: {e} | {tb}"


def add_fusion_generator(resolve, timeline_item_id: str, generator_name: str, settings: Dict[str, Any] = None) -> str:
    """
    Adds a Generator tool (like Text+, Background) via a Merge node.
    Flow: MediaIn -> Merge.Background; Generator -> Merge.Foreground; Merge -> MediaOut
    """
    project = resolve.GetProjectManager().GetCurrentProject()
    timeline = project.GetCurrentTimeline()
    if not timeline:
        return "Error: No current timeline"

    target_item = None
    track_count = timeline.GetTrackCount("video")
    for i in range(1, track_count + 1):
        items = timeline.GetItemListInTrack("video", i)
        if items:
            for item in items:
                if item.GetUniqueId() == timeline_item_id:
                    target_item = item
                    break
        if target_item:
            break

    if not target_item:
        return f"Error: Timeline item {timeline_item_id} not found"

    # FIX: Use latest composition
    comp_count = target_item.GetFusionCompCount()
    if comp_count == 0:
        target_item.AddFusionComp()
        comp_count = target_item.GetFusionCompCount()

    comp = target_item.GetFusionCompByIndex(comp_count)
    if not comp:
        return "Error: Could not get Fusion composition"

    logger.info(f"Adding generator '{generator_name}' to comp")

    try:
        gen_tool = comp.AddTool(generator_name)
        if not gen_tool:
            return f"Error: Failed to add tool '{generator_name}'."

        merge_tool = comp.AddTool("Merge")
        if not merge_tool:
            return "Error: Failed to add Merge tool."

        if settings:
            for key, val in settings.items():
                try:
                    if isinstance(val, dict) and "keyframes" in val:
                        kf_data = val["keyframes"]
                        init_cmd = f"{gen_tool.Name}.{key} = BezierSpline()"
                        comp.Execute(init_cmd)
                        for frame, kf_val in kf_data.items():
                            try:
                                f_num = float(frame)
                                if isinstance(kf_val, str):
                                    kf_cmd = f'{gen_tool.Name}.{key}[{f_num}] = "{kf_val}"'
                                else:
                                    kf_cmd = f"{gen_tool.Name}.{key}[{f_num}] = {kf_val}"
                                comp.Execute(kf_cmd)
                            except Exception:
                                pass
                    else:
                        gen_tool.SetInput(key, val)
                except Exception as ex:
                    logger.warning(f"Failed to set input {key}: {ex}")

        tool_list = comp.GetToolList(False)
        media_out = None
        media_in = None

        for _, tool in tool_list.items():
            if tool.ID == "MediaOut" or "MediaOut" in tool.Name:
                media_out = tool
            elif tool.ID == "MediaIn" or "MediaIn" in tool.Name:
                media_in = tool

        if media_out:
            # Fix: Check for existing input to MediaOut to chain effects
            current_input = media_out.GetInput("Input")

            if current_input:
                # If something is already connected to MediaOut, use THAT as background
                merge_tool.SetInput("Background", current_input)
            elif media_in:
                # Otherwise use MediaIn
                merge_tool.SetInput("Background", media_in.FindMainOutput(1))

            merge_tool.SetInput("Foreground", gen_tool.FindMainOutput(1))
            media_out.SetInput("Input", merge_tool.FindMainOutput(1))

            logger.info("Successfully wired generator via Merge.")
            return f"Added generator '{generator_name}'"

        return "Error: Could not find MediaOut to wire generator"

    except Exception as e:
        logger.error(f"Error adding generator: {e}")
        return f"Error adding generator: {e}"
